### ISSUE TITLE
能否省掉安装python模块那一步呢？

### ISSUE THREAD

**Issue by zifeixu85** [henter/Shanbay-Alfred2#1]
作为非技术人员，感觉很茫然啊

**Comment by henter** [comment]
@zifeixu85 新版很快会推出，谢谢关注

**Comment by henter** [comment]
@zifeixu85 新版可以用了，现在不需要安装模块。

网址：https://sbalfred.sinaapp.com/
下载：https://sbalfred.sinaapp.com/static/Shanbay.alfredworkflow

欢迎提bug，谢谢！

**Comment by zifeixu85** [comment]
谢谢这么快就更新了，赞~

问一下授权，我输入 "sbe test"  直接出现这个单词的例句了

**Comment by henter** [comment]
@zifeixu85 重新下载一下~  上次有点小bug

https://sbalfred.sinaapp.com/static/Shanbay.alfredworkflow

**Comment by henter** [comment]
昨天有个小bug，麻烦重新下载一下。。

https://sbalfred.sinaapp.com/static/Shanbay.alfredworkflow  

欢迎反馈~
:-)

## 

Henter
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
