### ISSUE TITLE
可否加一个创建自定义例句的功能

### ISSUE THREAD

**Issue by wonderffee** [henter/Shanbay-Alfred2#2]
帮你做了宣传 https://www.v2ex.com/t/216397
觉得有点小问题是不能创建自定义例句，能否添加一个呢，如果能加上我看到这个单词时的英文文章网页链接就更好了

**Comment by henter** [comment]
Hi，谢谢你的关注其实当时做这个Alfred插件时考虑过添加例句的功能，但是看了扇贝网API文档后还是放弃了。添加例句需要指定3项：单词 例句  译文，这对于Alfred来说操作成本比较高，也不太友好，所以放弃了。
谢谢你的反馈，如果有好的想法可以提出来一起聊聊 😃 
Sent from Outlook

On Thu, Aug 27, 2015 at 1:04 AM -0700, "wonderffee" notifications@github.com wrote:

帮你做了宣传 https://www.v2ex.com/t/216397，觉得有点小问题是不能创建自定义例句，能否添加一个呢，如果能加上我看到这个单词时的英文文章网页链接就更好了
