### ISSUE TITLE
授权不通过

### ISSUE THREAD

**Issue by limbo-lab** [henter/Shanbay-Alfred2#3]
![db5e5a05-4fa9-4818-8d01-0eb52e093a17](https://cloud.githubusercontent.com/assets/5107346/14198665/5f3e0faa-f80f-11e5-9eb9-c6f03e246dc1.png)

**Comment by henter** [comment]
@limbo-lab 忘记给新浪交保护费了。。现在恢复了
感谢反馈！

**Comment by rangerqu** [comment]
还是同样的状况呢

**Comment by henter** [comment]
@rangerqu 已恢复。
感谢反馈。

**Comment by alswl** [comment]
https 授权超了，我重写了一不用第三方网站的版本。

https://github.com/alswl/shanbay-alfred2

**Comment by henter** [comment]
@alswl nice :-)
