### ISSUE TITLE
页面未找到时 返回 url 不再为 token

### ISSUE THREAD

**Issue by xevilgenius** [henter/Shanbay-Alfred2#7]
变成了这么一个玩意：https://www.shanbay.com/oauth2/authorize/?client_id=7f652079ade6d4fa4eec&response_type=token

请问应该如何处理？还是他们就不提供了？之前发站内信问过，说是官方不再提供 token。不知现在是否这样曲线救国也不行了。

**Comment by henter** [comment]
官方不提供了。
